version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - bundle_path:/bundle
    environment:
      - BUNDLE_PATH=/bundle/vendor
      - RAILS_ENV=${RAILS_ENV:-development}
      - POSTGRES_HOST_AUTH_METHOD=postgres
    depends_on:
      - postgres
    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    ports:
      - '3000:3000'

  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres:
  bundle_path:
