default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: postgres
  user: postgres
  password: postgres
  port: 5432

development:
  <<: *default
  database: weight_monitor_development

test:
  <<: *default
  database: weight_monitor_test

production:
  <<: *default
  database: weight_monitor_production
  username: weight_monitor
  password: <%= ENV['WEIGHT_MONITOR_DATABASE_PASSWORD'] %>
