name: Tests & Coverage

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: Run Tests and Generate Coverage
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: weight_monitor_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:password@localhost:5432/weight_monitor_test
      REDIS_URL: redis://localhost:6379/0

    steps:
      # Setup
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      # Database and Assets
      - name: Setup database
        run: bin/rails db:setup

      - name: Precompile assets
        run: bundle exec rails assets:precompile

      # Coverage Data
      - name: Download master coverage artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          branch: master
          name: coverage
          path: coverage
        continue-on-error: true

      # Tests
      - name: Run RSpec tests with coverage report
        run: bundle exec rspec

      # Artifacts
      - name: Upload coverage results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage
          path: coverage/

      # Coverage Report
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: always()
        with:
          files: ./coverage/.resultset.json
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
